// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/bnema/openai-accounts-cli/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSelectionHistory creates a new instance of MockSelectionHistory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSelectionHistory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSelectionHistory {
	mock := &MockSelectionHistory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSelectionHistory is an autogenerated mock type for the SelectionHistory type
type MockSelectionHistory struct {
	mock.Mock
}

type MockSelectionHistory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSelectionHistory) EXPECT() *MockSelectionHistory_Expecter {
	return &MockSelectionHistory_Expecter{mock: &_m.Mock}
}

// RecentSelections provides a mock function for the type MockSelectionHistory
func (_mock *MockSelectionHistory) RecentSelections(ctx context.Context, since time.Time) ([]domain.AccountID, error) {
	ret := _mock.Called(ctx, since)

	if len(ret) == 0 {
		panic("no return value specified for RecentSelections")
	}

	var r0 []domain.AccountID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) ([]domain.AccountID, error)); ok {
		return returnFunc(ctx, since)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) []domain.AccountID); ok {
		r0 = returnFunc(ctx, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.AccountID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = returnFunc(ctx, since)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSelectionHistory_RecentSelections_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecentSelections'
type MockSelectionHistory_RecentSelections_Call struct {
	*mock.Call
}

// RecentSelections is a helper method to define mock.On call
//   - ctx context.Context
//   - since time.Time
func (_e *MockSelectionHistory_Expecter) RecentSelections(ctx interface{}, since interface{}) *MockSelectionHistory_RecentSelections_Call {
	return &MockSelectionHistory_RecentSelections_Call{Call: _e.mock.On("RecentSelections", ctx, since)}
}

func (_c *MockSelectionHistory_RecentSelections_Call) Run(run func(ctx context.Context, since time.Time)) *MockSelectionHistory_RecentSelections_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSelectionHistory_RecentSelections_Call) Return(accountIDs []domain.AccountID, err error) *MockSelectionHistory_RecentSelections_Call {
	_c.Call.Return(accountIDs, err)
	return _c
}

func (_c *MockSelectionHistory_RecentSelections_Call) RunAndReturn(run func(ctx context.Context, since time.Time) ([]domain.AccountID, error)) *MockSelectionHistory_RecentSelections_Call {
	_c.Call.Return(run)
	return _c
}

// RecordSelection provides a mock function for the type MockSelectionHistory
func (_mock *MockSelectionHistory) RecordSelection(ctx context.Context, id domain.AccountID, selectedAt time.Time) error {
	ret := _mock.Called(ctx, id, selectedAt)

	if len(ret) == 0 {
		panic("no return value specified for RecordSelection")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.AccountID, time.Time) error); ok {
		r0 = returnFunc(ctx, id, selectedAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSelectionHistory_RecordSelection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordSelection'
type MockSelectionHistory_RecordSelection_Call struct {
	*mock.Call
}

// RecordSelection is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.AccountID
//   - selectedAt time.Time
func (_e *MockSelectionHistory_Expecter) RecordSelection(ctx interface{}, id interface{}, selectedAt interface{}) *MockSelectionHistory_RecordSelection_Call {
	return &MockSelectionHistory_RecordSelection_Call{Call: _e.mock.On("RecordSelection", ctx, id, selectedAt)}
}

func (_c *MockSelectionHistory_RecordSelection_Call) Run(run func(ctx context.Context, id domain.AccountID, selectedAt time.Time)) *MockSelectionHistory_RecordSelection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.AccountID
		if args[1] != nil {
			arg1 = args[1].(domain.AccountID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSelectionHistory_RecordSelection_Call) Return(err error) *MockSelectionHistory_RecordSelection_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSelectionHistory_RecordSelection_Call) RunAndReturn(run func(ctx context.Context, id domain.AccountID, selectedAt time.Time) error) *MockSelectionHistory_RecordSelection_Call {
	_c.Call.Return(run)
	return _c
}
